from mortgage.sc.model import GeminiModelWrapper
from langchain_core.messages import HumanMessage

def chat(user_input: str) -> str:
    """Interacts with Gemini API and generates LLM-generated output.
    Args:
        user_input (str): User query
    Returns:
        str: Response generated by LLM
    """
    system_prompt = """You are a Mortgage agent. You are required to visit only the below-mentioned website and its subpages and links to answer any user's question.
Website: https://www.lloydsbank.com/mortgages.html
You must also be context-aware of what the user has asked in previous prompts.
Also provide structured output."""
    gemini = GeminiModelWrapper(sys_instruct=system_prompt)
    response = gemini.invoke([HumanMessage(content=user_input)])
    return response.content